### ISSUE TITLE
About the simplification algorithm

### ISSUE THREAD

**Issue by riyueshi** [vishalvijay18/Structure-Aware-Simplification#1]
Hi, vishalvijay18
  I find that the .pdf file in structure aware simplification cited the paper "Structure-Aware Mesh Decimation", Does this repository  implemented the algorithm in that paper ?

Miller

**Comment by vishalvijay18** [comment]
Hi Miller,

No. Though most of the concepts (especially structure preserving methods) were picked from the paper, Quadric calculations which we implemented were different from the one mentioned in that paper.

Vishal
